#!/usr/bin/env ruby

require 'socket'
require 'json'
require 'fileutils'
require 'time'
require 'yaml'
require 'pry' 

require_relative 'helper'
Dir[File.dirname(__FILE__) + '/lib/*.rb'].each {|file| require file }

CONFIG_FILE = ENV['HOME'] + '/.config/perhoa/config.yaml'

if File.file?(CONFIG_FILE)
  $config = symbolise(YAML.load_file(CONFIG_FILE))
else
  $config = symbolise(YAML.load_file('config.example.yaml'))
end

if already_running? 
  puts 'Sending messages to running Perhoa process...'
  send_message
  exit
end

read_arguments ARGV
read_config
run_socket
