#!/usr/bin/env ruby

require 'socket'
require 'fileutils'
require 'time'
require 'yaml'

Dir[File.dirname(__FILE__) + '/lib/*.rb'].each {|file| require file }

CONFIG_FILE = ENV['HOME'] + '/.config/perhoa/config.yaml'

$config = File.size?(CONFIG_FILE) ? symbolise(YAML.load_file(CONFIG_FILE)) : Hash.new

if already_running? 
  puts 'Sending messages to running Perhoa process...'
  send_message
  exit
end

read_arguments ARGV
read_config
run_socket
