#!/usr/bin/env ruby

require 'socket'
require 'fileutils'
require 'time'
require 'yaml'

Dir[File.dirname(__FILE__) + '/lib/*.rb'].each {|file| require file }

config_file = ENV['HOME'] + '/.config/perhoa/config.yaml'
config_file = File.file?(config_file) ? config_file :  'config.example.yaml'

$config = File.zero?(config_file) ? {} : symbolise(YAML.load_file(config_file))

if already_running? 
  puts 'Sending messages to running Perhoa process...'
  send_message
  exit
end

read_arguments ARGV
read_config
run_socket
